[versions]
minecraft = "1.20.2"
parchment_minecraft = "1.20.1"
parchment_mappings = "2023.08.20"

neoforge = "20.4.43-beta"

fabric_loader = "0.14.24"
fabric_api = "0.90.4+1.20.2"

mdg_plugin = "1.4.3"
mdg_dsl = "1.5.1"
autoservice = "1.1.1"

architectury_loom = "1.4.367"
quilt_licenser = "2.0.1"

jetbrains_annotations = "24.0.1"
jspecify = "0.3.0"

minotaur = "2.8.3"

owolib = "0.11.0+1.20"

managedversioning = "1.2.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

owolib = { module = "io.wispforest:owo-lib", version.ref = "owolib" }

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
mdg_plugin = { id = "org.groovymc.modsdotgroovy", version.ref = "mdg_plugin" }
architectury_loom = { id = "dev.architectury.loom", version.ref = "architectury_loom" }
quilt_licenser = { id = "org.quiltmc.gradle.licenser", version.ref = "quilt_licenser" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
curseforgegradle = {id = "net.darkhax.curseforgegradle", version = "1.1.16"}
